import Head from 'next/head';
import { MovieCard } from '@/types/Movie';
import MovieCardComponent from '@/components/movieCard';
import style from '../styles/Home.module.scss';
import Nav from '@/components/nav';
import { getFormattedMovies } from '@/services/MoviesService';

export default function Home({ movies }: { movies: MovieCard[] }) {
  return (
    <>
      <Head>
        <title>Movie ratings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className={style.cardGrid}>
        {movies.map((movie, index) => (
          <MovieCardComponent movie={movie} key={movie.id} index={index} />
        ))}
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const movies = await getFormattedMovies();
  return {
    props: {
      movies: movies,
    },
  };
}
